const socket=io(),saved=JSON.parse(localStorage.getItem("nexaFrontDeck")||localStorage.getItem("crownwarDeck")||"null"),$=id=>document.getElementById(id);let state=null,selected=null;
$("deckStatus").textContent=saved?`保存デッキ：${saved.king.name}／${saved.cards.length}枚`:"保存デッキがありません。";
$("joinButton").onclick=()=>{if(!saved)return alert("先にデッキを保存してください。");socket.emit("joinBattle",{roomName:$("roomName").value,playerName:$("playerName").value,kingId:saved.king.id,deckIds:saved.cards.map(c=>c.id)})};
socket.on("battleError",m=>{$("message").textContent=m;alert(m)});socket.on("battleState",s=>{state=s;$("lobby").hidden=true;$("game").hidden=false;selected=null;render()});
function unit(u,side,row,slot){const b=document.createElement("button");b.className="battle-unit"+(u?.tapped?" tapped":"");b.innerHTML=u?`<b>${u.name}</b><span>${u.atk||0} / ${u.currentHp}</span>`:"<span>空き</span>";b.onclick=()=>{if(u)showDetail(u);clickSlot(side,row,slot,u)};return b}
function makeRow(id,side,name){const el=$(id);el.innerHTML="";state.players[side].board[name].forEach((u,i)=>el.appendChild(unit(u,side,name,i)))}
function clickSlot(side,row,slot,u){if(state.turn!==state.you||state.winner!==null)return;if(selected?.kind==="hand")return socket.emit("playCard",{handIndex:selected.index,row,slot});if(side===state.you&&u){selected={kind:"unit",row,slot};render()}else if(side!==state.you&&u&&selected?.kind==="unit")socket.emit("attack",{row:selected.row,slot:selected.slot,targetRow:row,targetSlot:slot})}
function render(){const me=state.players[state.you],enemy=state.players[1-state.you],mine=state.turn===state.you;$("message").textContent=state.winner===null?`${state.message} ${mine?"あなたのターン":"相手のターン"}`:(state.winner===state.you?"勝利！":"敗北…");$("opponent").textContent=`${enemy.name}｜手札 ${enemy.handCount}｜山札 ${enemy.deckCount}`;$("enemyKing").textContent=`${enemy.king.name} HP ${enemy.hp}`;$("myKing").textContent=`${me.king.name} HP ${me.hp}｜忠誠 ${me.loyalty}`;$("enemyGrave").textContent=`墓地 ${enemy.graveCount}`;$("myGrave").textContent=`墓地 ${me.graveCount}`;$("enemyGrave").onclick=()=>openGrave(enemy,"相手の墓地");$("myGrave").onclick=()=>openGrave(me,"自分の墓地");$("enemyKing").onclick=()=>selected?.kind==="unit"&&socket.emit("attack",{row:selected.row,slot:selected.slot,king:true});makeRow("enemyBack",1-state.you,"back");makeRow("enemyFront",1-state.you,"front");makeRow("myFront",state.you,"front");makeRow("myBack",state.you,"back");const hand=$("hand");hand.innerHTML="<h3>手札</h3>";me.hand.forEach((c,i)=>{const b=document.createElement("button");b.className="hand-card"+(selected?.kind==="hand"&&selected.index===i?" selected":"");b.innerHTML=`<b>${c.name}</b><span>コスト ${c.cost}｜${c.type}</span><small>${c.text||""}</small>`;b.onclick=()=>{selected={kind:"hand",index:i};render()};hand.appendChild(b)});$("support").disabled=!mine||state.winner!==null||selected?.kind!=="unit"||selected.row!=="back";$("endTurn").disabled=!mine||state.winner!==null}
function openGrave(player,title){$("graveTitle").textContent=title;$("graveCards").innerHTML=player.grave.length?player.grave.map(c=>`<article><b>${c.name}</b><span>${c.type} / コスト ${c.cost}</span></article>`).join(""):"<p>墓地は空です。</p>";$("graveDialog").showModal()}
function showDetail(card){$("detailType").textContent=`${card.rarity||""} / ${card.type||""}`;$("detailName").textContent=card.name;$("detailStats").textContent=card.type==="Unit"?`コスト ${card.cost}　攻撃 ${card.atk||0}　体力 ${card.currentHp??card.hp}`:`コスト ${card.cost??"-"}`;$("detailText").textContent=card.text||"効果なし";$("cardDetail").hidden=false}
$("hand").addEventListener("click",()=>{if(selected?.kind==="hand")showDetail(state.players[state.you].hand[selected.index])});
$("closeDetail").onclick=()=>{$("cardDetail").hidden=true};
$("closeGrave").onclick=()=>$("graveDialog").close();
$("support").onclick=()=>selected?.row==="back"&&socket.emit("support",{slot:selected.slot});$("endTurn").onclick=()=>socket.emit("endTurn");$("surrender").onclick=()=>confirm("降参しますか？")&&socket.emit("surrender");
